### ISSUE TITLE
Make platform previews show up when editing

### ISSUE THREAD

**Issue by twboom** [twboom/FBWG-Editor#31]
When a platform is selected to edit (position or property editing) the preview of where the platform is going should be shown.

**Comment by twanman1412** [comment]
Platform previews now show up when editing or moving a platform and disappear when the pop-up is closed, unless platform previews is active via editor settings then they stay

**Comment by twboom** [comment]
The previews are only closed together with the popup box when the 'Close' button gets clicked, clicking outside the popup does close the box, but not the preview.

**Comment by twanman1412** [comment]
Platform previews now close when clicking off the popup
